### PR TITLE
Added Popular Posts without any plugin snippet

### PR DESCRIPTION
**Pull request by Bobeta**
References #2

### CODE REVIEW

**Comment by Mte90** [comment]
Uhm as snippet is not very powerful because don't consider spyder or spam bot, maybe an user agent check will power up that snippet.

**Comment by Bobeta** [comment]
I'm not sure I understand what you mean mate? The snippet is not supposed to be powerful. People tend to install extra plugins to showcase popular posts, this is a simple example of how they can do it on their own. I just updated the snippet for a better understanding.

**Comment by Mte90** [comment]
The purpose of the list is to have a collection of interesting snippets or something not easy to find or to do.
This one is very simple and every skilled wordpress developer can do it without many problems, so for me to add it in that list require to add an user agent check to empower the snippet itself.

**Comment by Bobeta** [comment]
Alright, I get it 👍  An idea idea would be to add a **contributing.md** file and specify guidelines for pull requests.

**Pull request closed without merging**
